language: node_js
node_js: stable
install: npm install

jobs:
  include:
    - stage: semantic release
      if: branch = master
      node_js: stable
      script: 
        - npm run build
        - npm run semantic-release
