language: node_js
node_js: stable
cache:
  directories:
    - build

install: npm install
script: npm run build

jobs:
  include:
    - stage: semantic release
      if: branch = master
      node_js: stable
      script: 
        - npm run semantic-release
    - stage: gh-pages
      if: branch = master 
      node_js: stable 
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN 
          keep_history: true
          local_dir: build/ 
